config/routes.rb
Rails.application.routes.draw do
  get 'student/index'

  get 'student/new'
  post 'student/new'
  
  get 'student/show'
  get 'student/edit'
  get 'student/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/learner.rb
class Learner < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  def index
    @students = Learner.all
  end

  def show
    @students = Learner.all
  end

  def edit
  end

  def destroy
    @student.destroy

    respond_to do |format|
      redirect_to students_url
      flash[:notice]= "student is successfully destroyed." 
      # format.json { head :no_content }
    end
  end

  def new
    @learner = Learner.new(student_params)
    if request.post?
      if @learner.save
        flash[:notice] = "New student data is created"
        redirect_to :action=>show
      end
    end
  end

  private
  def student_params
    params.permit(:name, :age, :mark1, :mark2, :mark3, :mark4, :mark5, :grade)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentReport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/student/_form.html.erb
<%= form_with url:"/student/new" , method: :post do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h4>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age%>
    <%= form.number_field :age%>
  </div>


  <div class="field">
    <%= form.label :mark1%>
    <%= form.number_field :mark1%>
  </div>

  <div class="field">
    <%= form.label :mark2%>
    <%= form.number_field :mark2%>
  </div>

  <div class="field">
    <%= form.label :mark3%>
    <%= form.number_field :mark3%>
  </div>

  <div class="field">
    <%= form.label :mark4%>
    <%= form.number_field :mark4%>
  </div>

  <div class="field">
    <%= form.label :mark5%>
    <%= form.number_field :mark5%>
  </div>

  <div class="field">
    <%= form.label :grade%>
    <%= form.text_field :grade%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student/destroy.html.erb
<h1>Student#destroy</h1>
<p>Find me in app/views/student/destroy.html.erb</p>

app/views/student/edit.html.erb
<h1>Student#edit</h1>
<p>Find me in app/views/student/edit.html.erb</p>

app/views/student/index.html.erb
<p id="notice"> <%= notice%> </p>

<h1>Student Data Table </h1>

<table> 
    <thead> 
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Mark1</th>
            <th>Mark2</th>
            <th>Mark3</th>
            <th>Mark4</th>
            <th>Mark5</th>
            <th>Grade</th>
            <th colspan="3" ></th>
        </tr>
    </thead>

    <tbody>
        <% @students.each do |student| %>
            <tr>
                <td> <%= student.name%> </td>
                <td> <%= student.age%> </td>
                <td> <%= student.mark1%> </td>
                <td> <%= student.mark2%> </td>
                <td> <%= student.mark3%> </td>
                <td> <%= student.mark4%> </td>
                <td> <%= student.mark5%> </td>
                <td> <%= student.grade%> </td>
                <td> <%= link_to 'Show' , student_show_path(student) %>   </td> 
                <td> <%= link_to 'Edit' , student_edit_path(student) %> </td>
                <td> <%= link_to 'Delete', student_destroy_path(student) , method: :delete, data: {confirm: 'Are you sure?'}%>   </td>
            </tr>
        <%end%>
    </tbody>
</table>

<br>

<%= link_to 'New Student' , student_new_path %>
<%# new_student_path %>

app/views/student/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @learner %>

<%= link_to 'Back', student_index_path %>

app/views/student/show.html.erb
<p id="notice"><%= notice %></p>

<%= @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
    </tr>
  <% end %>

<p>
  <strong>Age:</strong>
  <%# <%= @students.student.age %> %>
</p>

<p>
  <strong>mark1:</strong>
  <%# <%= @students.mark1 %> %>
</p>
<p>
  <strong>mark2:</strong>
  <%# <%= @students.mark2 %> %>
</p>
<p>
  <strong>mark3:</strong>
  <%# <%= @students.mark3 %> %>
</p>

<p>
  <strong>mark4:</strong>
  <%# <%= @students.mark4 %> %>
</p>
<p>
  <strong>mark5:</strong>
  <%# <%= @students.mark5 %> %>
</p>


<p>
  <strong>Grade:</strong>
  <%# <%= @students.grade %> %>
</p>